
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5 #<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: time_talker_development

test:
  <<: *default
  database: time_talker_test